apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}
  labels:
    app: {{ .Values.projectName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.projectName }}
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}
    spec:
      containers:
      - name: {{ .Values.projectName }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: {{ .Values.container.port }}