apiVersion: v2
name: rabbitmq
description: A Helm chart for RabbitMQ
type: application
version: 0.1.0
dependencies:
  - name: rabbitmq
    version: 13.0.3
    repository: https://charts.bitnami.com/bitnami