apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ui
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vault.localhost`) && (PathPrefix(`/ui`) || PathPrefix(`/v1`))
      kind: Rule
      services:
        - name: vault
          port: 8200