apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`alertmanager.localhost`)
    kind: Rule
    services:
    - name: prometheus-kube-prometheus-alertmanager
      port: 9093