apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
spec:
    entryPoints:
        - web
    routes:
    - match: Host(`prometheus.{{.Values.domain}}`)
      kind: Rule
      services:
      - name: {{ .Release.Name }}-prometheus
        port: 9090