apiVersion: v2
name: kibana
description: A Helm chart for Kibana
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: kibana
    version: 8.5.1
    repository: https://helm.elastic.co