apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: influxdb
spec:
    entryPoints:
        - web
    routes:
        - match: Host(`influx.{{ .Values.domain }}`)
          kind: Rule
          services:
          - name: influxdb
            port: 8086