apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rabbitmq
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`rabbitmq.localhost`)
    kind: Rule
    services:
    - name: rabbitmq
      port: 15672